server:
  address: 0.0.0.0
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: steam-tracker

  datasource:
    url: jdbc:mysql://localhost:3306/steam_tracker?serverTimezone=Asia/Seoul
    username: steamuser
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true